### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ruuts** [bookingexperts/translator#1]
@everplays can you add updated instructions for exporting / importing translations?

**Comment by MaureenIlboga** [comment]
@everplays can i check this?

**Comment by everplays** [comment]
@MaureenIlboga no. Probably, this project shouldn't be on waffle at all.

**Comment by MaureenIlboga** [comment]
@everplays strange. I am not able to add a filter or anything so i can't remove it. Can you?

**Comment by everplays** [comment]
@MaureenIlboga no. @ruuts should do it.

**Comment by ruuts** [comment]
@MaureenIlboga I don't get it. You see this issue in waffle? I don't. Can you make a screenshot?
